### ISSUE TITLE
Performance: GetHostByName calls

### ISSUE THREAD

**Issue by FlorianHeigl** [Mokkujin/Checks-for-Check_MK#1]
Hi,

i'm hacking with your plugin a bit. It's tricky since I don't actually know powershell or windows well enough, but I'm pretty certain I found an improvement.

in `script:Test-Quota` you resolve `$ServerName` using a DNS lookup for the $env:computername.
I don't know exactly the reason for the lookup but I am pretty certain you could move it out of the function to the main script.
The difference is that, as is, it'll run the lookup once per quota entry.
Since it's a DNS call this actually has to call out to the configured DNS, so it'll stop processing for that call each round.

**Comment by FlorianHeigl** [comment]
you can check what I changed here:
https://gist.github.com/FlorianHeigl/7eb4c655af1b0f6f3583dd0d2e0f6cc2

I suppose it would be good to cache/keep open the `Get-SmbShare` call/instance , but I don't know how do to that.

I had a lot of non-share quotas so the incrementing of LocalQuota++ made it confusing for the human eye.
so I skip over them for the moment.

Please check back in a few days, I got graphs now, but warn/crit lines seem to not get drawn yet.

Finally: Thank you - the new check worked a lot better and it was written clearly enough so I could modify it myself.

**Comment by Mokkujin** [comment]
thx for your input :) 
I removed the $script:ServerName from the function , your right its enough to check it on start ;) But in my case i need the full qualified domain name and $env:computername is not enough.

for you second issue i created a var named $script:SharesOnly if ir $true no local folders will be reported , an here again in my usecase i need the local folders without share too

**Comment by Mokkujin** [comment]
I hope the new version to show local quotas is better for u ;)
